name: ExampleRemarkPlugin
author: DiamondStrider1
main: DiamondStrider1\ExampleRemarkPlugin\Plugin
api: 4.0.0
version: 1.1.0

permissions:
    example.command:
        default: true
    example.command.see:
        default: true
    example.command.survey:
        default: true
    example.command.dance:
        default: true
